let arr = [1, 88, 45, 82, 23];
console.log(arr);
console.log(arr.toString());
console.log(arr.join(" "));
console.log(arr.pop());
console.log(arr);
console.log(arr.push(1000));
console.log(arr);
console.log(arr.shift());
console.log(arr);
console.log(arr.unshift(90000));
console.log(arr);
console.log(arr.concat([8,7,6,5,1,11]));
console.log(arr.sort());
arr.splice(2, 2);
console.log(arr);
console.log(arr.reverse());